/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import domain.Company;
import domain.Helper;
import domain.Player;
import exceptions.AllConfiguredPlayersAreNotSelectedException;
import exceptions.ThereAreNotPlayersCreatedException;
import exceptions.ThereAreNotPlayersLeftToSelectException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class WindowMainMenu extends javax.swing.JFrame {

    private Company company;
    private Helper helper;

    /**
     * when the window instance is created, the components are initialized,
     * properties of the window are defined as if it closes all the windows that
     * are open must be closed Creates new form WindowMainMenu
     */
    public WindowMainMenu(Company company) {
        this.company = company;
        initComponents();
        this.helper = new Helper();
        this.setSize(700, 500);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelMenu = new javax.swing.JLabel();
        buttonDefineSpecialSettings = new javax.swing.JButton();
        buttonCreateANewPlayer = new javax.swing.JButton();
        buttonSelectAPlayerCreated = new javax.swing.JButton();
        buttonPlay = new javax.swing.JButton();
        buttonListByPlayer = new javax.swing.JButton();
        buttonEnd = new javax.swing.JButton();
        buttonGenerateTheFileDiferentes = new javax.swing.JButton();
        buttonGenerateFileExcel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelMenu.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        labelMenu.setText(" Menu");

        buttonDefineSpecialSettings.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        buttonDefineSpecialSettings.setText("1. Define a special settings");
        buttonDefineSpecialSettings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonDefineSpecialSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDefineSpecialSettingsActionPerformed(evt);
            }
        });

        buttonCreateANewPlayer.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        buttonCreateANewPlayer.setText("2. Create a new player");
        buttonCreateANewPlayer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonCreateANewPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateANewPlayerActionPerformed(evt);
            }
        });

        buttonSelectAPlayerCreated.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        buttonSelectAPlayerCreated.setText("3. Select a player created");
        buttonSelectAPlayerCreated.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonSelectAPlayerCreated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelectAPlayerCreatedActionPerformed(evt);
            }
        });

        buttonPlay.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        buttonPlay.setText("4. Play");
        buttonPlay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlayActionPerformed(evt);
            }
        });

        buttonListByPlayer.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        buttonListByPlayer.setText("5. List by player");
        buttonListByPlayer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonListByPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonListByPlayerActionPerformed(evt);
            }
        });

        buttonEnd.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        buttonEnd.setText("7. End");
        buttonEnd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEndActionPerformed(evt);
            }
        });

        buttonGenerateTheFileDiferentes.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        buttonGenerateTheFileDiferentes.setText("6. Generate the file DIFERENTES.txt");
        buttonGenerateTheFileDiferentes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonGenerateTheFileDiferentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenerateTheFileDiferentesActionPerformed(evt);
            }
        });

        buttonGenerateFileExcel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 11)); // NOI18N
        buttonGenerateFileExcel.setText("7. Generate file Excel");
        buttonGenerateFileExcel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonGenerateFileExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenerateFileExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(labelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonListByPlayer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPlay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSelectAPlayerCreated, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCreateANewPlayer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonDefineSpecialSettings, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonGenerateTheFileDiferentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonGenerateFileExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonDefineSpecialSettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCreateANewPlayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSelectAPlayerCreated)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonPlay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonListByPlayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonGenerateTheFileDiferentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonGenerateFileExcel)
                .addGap(7, 7, 7)
                .addComponent(buttonEnd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * *
     * the definespecialsettings window opens
     *
     * @param evt
     */
    private void buttonDefineSpecialSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDefineSpecialSettingsActionPerformed
        // TODO add your handling code here:
        WindowDefineASpecialSettings windowDefineASpecialSettings = new WindowDefineASpecialSettings(company);
        windowDefineASpecialSettings.setVisible(true);
    }//GEN-LAST:event_buttonDefineSpecialSettingsActionPerformed

    /**
     * *
     * the createanewplayer window opens
     *
     * @param evt
     */
    private void buttonCreateANewPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateANewPlayerActionPerformed
        // TODO add your handling code here:
        WindowCreateANewPlayer windowCreateANewPlayer = new WindowCreateANewPlayer(company);
        windowCreateANewPlayer.setVisible(true);

    }//GEN-LAST:event_buttonCreateANewPlayerActionPerformed
    /**
     * *
     * it is validated there are players to show, in case no exception is
     * thrown, in case if the window is opened
     *
     * @param evt
     */
    private void buttonListByPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListByPlayerActionPerformed
        // TODO add your handling code here:
        try {
            company.validateThereArePlayersCreated();
            WindowListByPlayer windowListByPlayer = new WindowListByPlayer(company);
            windowListByPlayer.setVisible(true);
        } catch (ThereAreNotPlayersCreatedException ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_buttonListByPlayerActionPerformed
    /**
     * *
     * it is validated if all the configured players were selected, in case no
     * exception is thrown, in case if the window is opened
     *
     * @param evt
     */
    private void buttonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlayActionPerformed
        // TODO add your handling code here:
        WindowGame windowGame = new WindowGame(this.company);
        try {
            company.getGame().validateAllConfiguredPlayersAreSelected();
            windowGame.setVisible(true);
        } catch (AllConfiguredPlayersAreNotSelectedException ex) {
            ex.getMessage();
        }

    }//GEN-LAST:event_buttonPlayActionPerformed
    /**
     * *
     * it is validated if there are players created, in case no exception is
     * thrown, in case if the window is opened
     *
     * @param evt
     */
    private void buttonSelectAPlayerCreatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelectAPlayerCreatedActionPerformed
        try {
            // TODO add your handling code here:
            company.validateThereArePlayersCreated();
            company.getGame().validateAreTherePlayersLeftToSelect();
            WindowSelectAPlayerCreated windowSelectAPlayerCreated = new WindowSelectAPlayerCreated(company);
            windowSelectAPlayerCreated.setVisible(true);
        } catch (ThereAreNotPlayersLeftToSelectException | ThereAreNotPlayersCreatedException ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_buttonSelectAPlayerCreatedActionPerformed
    /**
     * *
     * a window opens that allows the user to choose the file and the file
     * DIFERENTES.txt is generated
     *
     * @param evt
     */
    private void buttonGenerateTheFileDiferentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenerateTheFileDiferentesActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int select = fileChooser.showOpenDialog(this);
        if (select == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            helper.generateFileDifferentPlayers(file, company);
            JOptionPane.showMessageDialog(null, "File created correctly", "", 1);
        }
    }//GEN-LAST:event_buttonGenerateTheFileDiferentesActionPerformed
    /**
     * the whole program closes
     *
     * @param evt
     */
    private void buttonEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEndActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_buttonEndActionPerformed

    private void buttonGenerateFileExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenerateFileExcelActionPerformed
        // TODO add your handling code here:
        PrintWriter pw = null;
        try {
            pw = new PrintWriter(new File("players.csv"));
            StringBuilder sb = new StringBuilder();
            for(int i=0; i<company.getListCreatedPlayers().size(); i++){
              Player  player = company.getListCreatedPlayers().get(i);
              sb.append("name: "+player.getName()+", alias: "+player+", age: "+player.getAge()+","
              + " quantity of games against 1 player: "+player.getQuantityOpponents()[0]+", quantity of games against 2 players: "+player.getQuantityOpponents()[1]+", quantity of games against 3 players"+ 
                      player.getQuantityOpponents()[2]+", quantity of games against 4 players"+player.getQuantityOpponents()[3]+", quantity of games won: "+player.getQuantityGamesWon());
              sb.append('\n');
            }
            
            pw.write(sb.toString());
            pw.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(WindowMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "File created correctly", "", 1);
    }//GEN-LAST:event_buttonGenerateFileExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new WindowMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreateANewPlayer;
    private javax.swing.JButton buttonDefineSpecialSettings;
    private javax.swing.JButton buttonEnd;
    private javax.swing.JButton buttonGenerateFileExcel;
    private javax.swing.JButton buttonGenerateTheFileDiferentes;
    private javax.swing.JButton buttonListByPlayer;
    private javax.swing.JButton buttonPlay;
    private javax.swing.JButton buttonSelectAPlayerCreated;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelMenu;
    // End of variables declaration//GEN-END:variables
}
